spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/signup?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=PST
#    username: root
#    password: test1234
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      ddl-auto: validate
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#  flyway:
#    enabled: true
#    baselineOnMigrate: true
#    baseline-version: 00.00.00.00
server:
  port: 8091
